# Generated by Django 2.2.24 on 2022-12-21 17:29

from django.db import migrations
import phonenumbers

def fill_owner_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all().iterator():
        if not flat.owners_phonenumber:
            continue
        parsed_phone = phonenumbers.parse(flat.owners_phonenumber, 'RU')

        if not phonenumbers.is_valid_number(parsed_phone):
            continue
        flat.owners_pure_phone = phonenumbers.format_number(parsed_phone, phonenumbers.PhoneNumberFormat.E164)
        flat.save()


def move_backward(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    for flat in Flat.objects.all():
        flat.owners_pure_phone = None
        flat.save()

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0007_flat_owners_pure_phone'),
    ]

    operations = [
        migrations.RunPython(fill_owner_pure_phone, move_backward)
    ]
