# Generated by Django 2.2.24 on 2022-12-17 19:00

from django.db import migrations


def load_owners(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property','Owner')
    for flat in Flat.objects.all():
        Owner.objects.get_or_create(owner_pure_phone=flat.owner_pure_phone, defaults={
            'name': flat.owner,
            'owners_phonenumber': flat.owners_phonenumber,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_owner'),
    ]

    operations = [
        migrations.RunPython(load_owners),
    ]
