# Generated by Django 2.2.24 on 2022-12-21 18:55

from django.db import migrations

def load_flats(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property','Owner')
    for flat in Flat.objects.all().iterator():
        owner = Owner.objects.get_or_create(name=flat.owner, pure_phone=flat.owners_pure_phone)
        owner_flat = owner[0].flats
        owner_flat.set([flat])

def load_flat_owners(apps, schema_editor):
    Flat = apps.get_model('property','Flat')
    Owner = apps.get_model('property','Owner')
    for owner in Owner.objects.all().iterator():
        flat = Flat.objects.get_or_create(owner=owner.name, owners_pure_phone=owner.pure_phone)
        flat_owner = flat[0].owner
        flat_owner.set([owner])


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_auto_20221221_2140'),
    ]

    operations = [
        migrations.RunPython(load_flats, load_flat_owners, ),
    ]
